name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Obtener el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Paso 3: Cachear dependencias de pip
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      # Paso 4: Crear el archivo .env con los secrets
      - name: Create .env file
        run: |
          echo "URL=${{ secrets.API_URL }}" > .env
          echo "DB=${{ secrets.API_DB }}" >> .env
          echo "USERNAME=${{ secrets.API_USERNAME }}" >> .env
          echo "PASSWORD=${{ secrets.API_PASSWORD }}" >> .env
          # Agregar más variables si es necesario
        shell: bash
        
      #Testeo de creación de variables en .env (Debug)
      - name: Show environment variables (safe subset)
        run: env | grep -E "URL|DB|USERNAME|PASSWORD"
        
      # Paso 4: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Paso 5: Ejecutar los tests
      - name: Run tests
        run: pytest
