name: Build and Test CamLink Docker

on:
  push:
    branches:
      - stable
  pull_request:
    branches:
      - stable

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Chequea el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura Python y las dependencias
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12  # Asegúrate de usar la versión que necesitas

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # 3. Ejecuta los tests unitarios
      - name: Run Tests
        run: |
          pytest ./src/utils/tests/
          
      # 4. Construye la imagen de Docker
      - name: Build Docker Image
        run: docker build -t ghcr.io/gonzaloaltatec/camlink/camlink:latest .

      # 5. Ejecuta la imagen de Docker y verifica que la API esté activa
      - name: Run Docker Container
        run: |
          docker run -d -p 8000:8000 --name camlink-container camlink
          sleep 10  # Espera a que el servicio se inicie
          curl --fail http://localhost:8000/ || exit 1
          
      # 6. Limpia el contenedor
      - name: Cleanup
        run: docker rm -f camlink-container

      # 7. Inicia sesión en GitHub Packages
      - name: Log in to GitHub Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 8. Publica la imagen en GitHub Packages
      - name: Push Docker Image to GitHub Packages
        run: docker push ghcr.io/gonzaloaltatec/camlink/camlink:latest
